### ISSUE TITLE
Canvas rendering not crisp on HDPI screens

### ISSUE THREAD

**Issue by mdamien** [Linkurious/linkurious.js#232] opened 2015-08-03 12:24 UTC
Here's the svg renderer compared to the canvas renderer:

![image](https://cloud.githubusercontent.com/assets/1469823/9037383/1eea0a90-39eb-11e5-8a7d-3f5399fabda4.png)

It's especially visible on the labels.

The fix is to double the resolution of the canvas if it's an HDPI screen:

``` 

    canvas.getContext('2d').scale(ratio,ratio) before each render
```

**Comment by sheymann** [comment] 2015-08-03 12:29
Duplicate of #25

**Closed** 2015-08-03 12:30 UTC
Labels: status:duplicate
