### ISSUE TITLE
CSV and Gephi Exports broken in Safari

### ISSUE THREAD

**Issue by emergingdzns** [Linkurious/linkurious.js#183] opened 2015-07-16 23:07 UTC
In Safari, when using the csv export functions, it does not prompt to download the CSV files. It just barfs the data out onto the page.

The gexf export actually throws an xml error:
```
This page contains the following errors:

error on line 1 at column 89: xmlns:schemaLocation: 'http://www.gexf.net/1.2draft http://www.gexf.net/1.2draft/gexf.xsd' is not a valid URI
Below is a rendering of the page up to the first error.
```
Both of the export functions are set to `{download: true}` as well. Other browsers don't seem to have an issue with it.

Any way to fix this?

**Comment by apitts** [comment] 2015-07-17 00:12
@emergingdzns I believe this may be related to a known issue in Safari that I too recently ran into:
https://bugs.webkit.org/show_bug.cgi?id=102914

See this link for some suggestions (but ultimately you may just want to open an alert and tell the user to use a different browser if this is the issue you are facing):
https://github.com/eligrey/FileSaver.js/issues/12

**Comment by sheymann** [comment] 2015-07-17 07:42
Seems a duplicate of #162, please update to the latest code of linkurious.js

`xmlns:schemaLocation` is now `xsi:schemaLocation`

**Comment by sheymann** [comment] 2015-07-17 16:42
After fighting a lot against Safari, I've abandonned as well. This browser is rotten.

http://arstechnica.com/information-technology/2015/06/op-ed-safari-is-the-new-internet-explorer/

**Closed by sheymann** 2015-07-17 16:42 UTC
Labels: status:wontfix, type:bug, where:plugin
